# Generated by Django 5.0.6 on 2026-07-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='ats_uploads/')),
                ('job_description', models.TextField(blank=True)),
                ('overall_score', models.IntegerField(default=0)),
                ('content_score', models.IntegerField(default=0)),
                ('format_score', models.IntegerField(default=0)),
                ('keyword_score', models.IntegerField(default=0)),
                ('structure_score', models.IntegerField(default=0)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('section_feedback', models.JSONField(blank=True, default=dict)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ATS Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_color', models.CharField(default='blue', max_length=20)),
                ('professional_title', models.CharField(blank=True, max_length=150)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='resume_templates/')),
                ('color_options', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
